#FROM   postgres
#ENV    POSTGRES_PASSWORD postgres
#CMD    CREATE TABLE employee (id serial NOT NULL,name character varying(200) NOT NULL,job character varying(200) NOT NULL,department character varying(20) NOT NULL,salary int NOT NULL,hire_date date NOT NULL);
#CMD    []

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
          - testdb:/var/lib/postgresql/data
          - ./table.sql:/docker-entrypoint-initdb.d/table.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb

  nodejs:
    build:
       context: .
#    container_name: employees
    ports:
      - "4000:4000"
#    environment:
#       connectionString: "postgres://postgres:postgres@localhost:5432/testdb"
    depends_on:
      - postgres
    links:
      - postgres
volumes:
    testdb:
